import { useEffect, useMemo, useRef, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { useAuth } from "@/contexts/AuthContext";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { useToast } from "@/hooks/use-toast";
import {
  CheckCircle2,
  Loader2,
  MoreHorizontal,
  Search,
  UserPlus,
  Users,
  Users2,
  X,
} from "lucide-react";
import type { Database } from "@/integrations/supabase/types";
import AppLayout from "@/components/layout/AppLayout";
import { cn } from "@/lib/utils";
import SquadTab from "@/components/friends/SquadTab";
import { getRankIcon } from "@/lib/rankIcons";

type FriendRequest = Database["public"]["Tables"]["friend_requests"]["Row"];
type FriendProfile = {
  user_id: string;
  username: string;
  rl_account_name: string | null;
  avatar_url: string | null;
};

const RANK_TIER_ORDER = [
  "unranked",
  "bronze_1", "bronze_2", "bronze_3",
  "silver_1", "silver_2", "silver_3",
  "gold_1", "gold_2", "gold_3",
  "platinum_1", "platinum_2", "platinum_3",
  "diamond_1", "diamond_2", "diamond_3",
  "champion_1", "champion_2", "champion_3",
  "grand_champion_1", "grand_champion_2", "grand_champion_3",
  "supersonic_legend",
];

const RANK_LABELS: Record<string, string> = {
  unranked: "Unranked",
  bronze_1: "Bronze I", bronze_2: "Bronze II", bronze_3: "Bronze III",
  silver_1: "Silver I", silver_2: "Silver II", silver_3: "Silver III",
  gold_1: "Gold I", gold_2: "Gold II", gold_3: "Gold III",
  platinum_1: "Plat I", platinum_2: "Plat II", platinum_3: "Plat III",
  diamond_1: "Diamond I", diamond_2: "Diamond II", diamond_3: "Diamond III",
  champion_1: "Champ I", champion_2: "Champ II", champion_3: "Champ III",
  grand_champion_1: "GC I", grand_champion_2: "GC II", grand_champion_3: "GC III",
  supersonic_legend: "SSL",
};

const RANK_COLORS: Record<string, string> = {
  unranked: "text-muted-foreground",
  bronze_1: "text-amber-700", bronze_2: "text-amber-700", bronze_3: "text-amber-700",
  silver_1: "text-slate-400", silver_2: "text-slate-400", silver_3: "text-slate-400",
  gold_1: "text-yellow-400", gold_2: "text-yellow-400", gold_3: "text-yellow-400",
  platinum_1: "text-cyan-400", platinum_2: "text-cyan-400", platinum_3: "text-cyan-400",
  diamond_1: "text-blue-400", diamond_2: "text-blue-400", diamond_3: "text-blue-400",
  champion_1: "text-purple-400", champion_2: "text-purple-400", champion_3: "text-purple-400",
  grand_champion_1: "text-red-400", grand_champion_2: "text-red-400", grand_champion_3: "text-red-400",
  supersonic_legend: "text-primary",
};

const getDisplayName = (p?: FriendProfile | null) =>
  p?.rl_account_name?.trim() || p?.username || "Unknown";

const isAutoGeneratedUsername = (value?: string | null) =>
  Boolean(value && /^user_[a-z0-9]+$/i.test(value));

const shouldShowUsername = (p?: FriendProfile | null) => {
  if (!p?.username) return false;
  if (isAutoGeneratedUsername(p.username)) return false;
  return p.username !== p.rl_account_name?.trim();
};

// Avatar circle with initials fallback
const Avatar = ({
  src,
  name,
  size = "md",
}: {
  src: string | null;
  name: string;
  size?: "sm" | "md" | "lg";
}) => {
  const sizeClass = size === "sm" ? "w-8 h-8 text-[10px]" : size === "lg" ? "w-11 h-11 text-sm" : "w-10 h-10 text-xs";
  const initials = name.slice(0, 2).toUpperCase();
  return (
    <div className={cn("rounded-full border-2 border-border/60 bg-muted/60 overflow-hidden shrink-0 flex items-center justify-center font-bold text-muted-foreground", sizeClass)}>
      {src ? (
        <img src={src} alt={name} className="w-full h-full object-cover" />
      ) : (
        <span>{initials}</span>
      )}
    </div>
  );
};

type PageTab = "friends" | "squad";

const Friends = () => {
  const { user, loading: authLoading } = useAuth();
  const navigate = useNavigate();
  const { toast } = useToast();

  const [pageTab, setPageTab] = useState<PageTab>("friends");
  const [loading, setLoading] = useState(true);
  const [friendRequests, setFriendRequests] = useState<FriendRequest[]>([]);
  const [friendProfiles, setFriendProfiles] = useState<FriendProfile[]>([]);
  const [friendRanks, setFriendRanks] = useState<Map<string, string>>(new Map());
  const [searchQuery, setSearchQuery] = useState("");
  const [searchResults, setSearchResults] = useState<FriendProfile[]>([]);
  const [searchRanks, setSearchRanks] = useState<Map<string, string>>(new Map());
  const [searching, setSearching] = useState(false);
  const [actionId, setActionId] = useState<string | null>(null);
  const [justSent, setJustSent] = useState<Set<string>>(new Set());
  const debounceRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  useEffect(() => {
    if (!authLoading && !user) navigate("/auth");
  }, [user, authLoading, navigate]);

  const refresh = async () => {
    if (!user) return;
    setLoading(true);
    try {
      const { data: requests, error } = await supabase
        .from("friend_requests")
        .select("id, sender_id, receiver_id, status, created_at, updated_at")
        .or(`sender_id.eq.${user.id},receiver_id.eq.${user.id}`)
        .in("status", ["pending", "accepted"]);
      if (error) throw error;

      const reqs = requests || [];
      setFriendRequests(reqs);

      const otherIds = Array.from(
        new Set(reqs.map((r) => (r.sender_id === user.id ? r.receiver_id : r.sender_id)))
      ).filter(Boolean);

      if (otherIds.length > 0) {
        const [{ data: profiles }, { data: ranksData }] = await Promise.all([
          supabase.from("profiles").select("user_id, username, rl_account_name, avatar_url").in("user_id", otherIds),
          supabase.from("ranks").select("user_id, rank_tier").in("user_id", otherIds).eq("game_type", "competitive"),
        ]);

        setFriendProfiles((profiles || []) as FriendProfile[]);

        // Build highest-rank map per user
        const rankMap = new Map<string, string>();
        (ranksData || []).forEach((r) => {
          if (!r.rank_tier) return;
          const existing = rankMap.get(r.user_id);
          if (
            !existing ||
            RANK_TIER_ORDER.indexOf(r.rank_tier) > RANK_TIER_ORDER.indexOf(existing)
          ) {
            rankMap.set(r.user_id, r.rank_tier);
          }
        });
        setFriendRanks(rankMap);
      } else {
        setFriendProfiles([]);
        setFriendRanks(new Map());
      }
    } catch (err: any) {
      toast({ title: "Failed to load friends", description: err.message, variant: "destructive" });
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { if (user) refresh(); }, [user]);

  // Debounced search
  useEffect(() => {
    if (debounceRef.current) clearTimeout(debounceRef.current);
    const q = searchQuery.trim();
    if (!q) { setSearchResults([]); setSearchRanks(new Map()); return; }
    debounceRef.current = setTimeout(async () => {
      if (!user) return;
      setSearching(true);
      try {
        const { data, error } = await supabase
          .from("profiles")
          .select("user_id, username, rl_account_name, avatar_url")
          .or(`username.ilike.%${q}%,rl_account_name.ilike.%${q}%`)
          .neq("user_id", user.id)
          .limit(8);
        if (error) throw error;
        const results = (data || []) as FriendProfile[];
        setSearchResults(results);

        // Fetch ranks for search results
        if (results.length > 0) {
          const { data: ranksData } = await supabase
            .from("ranks")
            .select("user_id, rank_tier")
            .in("user_id", results.map((r) => r.user_id))
            .eq("game_type", "competitive");
          const rankMap = new Map<string, string>();
          (ranksData || []).forEach((r) => {
            if (!r.rank_tier) return;
            const existing = rankMap.get(r.user_id);
            if (!existing || RANK_TIER_ORDER.indexOf(r.rank_tier) > RANK_TIER_ORDER.indexOf(existing)) {
              rankMap.set(r.user_id, r.rank_tier);
            }
          });
          setSearchRanks(rankMap);
        }
      } catch (err: any) {
        toast({ title: "Search failed", description: err.message, variant: "destructive" });
      } finally {
        setSearching(false);
      }
    }, 350);
    return () => { if (debounceRef.current) clearTimeout(debounceRef.current); };
  }, [searchQuery, user]);

  const profileMap = useMemo(
    () => new Map(friendProfiles.map((p) => [p.user_id, p])),
    [friendProfiles]
  );
  const incoming = useMemo(
    () => friendRequests.filter((r) => r.status === "pending" && r.receiver_id === user?.id),
    [friendRequests, user?.id]
  );
  const outgoing = useMemo(
    () => friendRequests.filter((r) => r.status === "pending" && r.sender_id === user?.id),
    [friendRequests, user?.id]
  );
  const accepted = useMemo(
    () => friendRequests.filter((r) => r.status === "accepted"),
    [friendRequests]
  );

  const findRequestWith = (targetId: string) =>
    friendRequests.find(
      (r) => (r.sender_id === user?.id && r.receiver_id === targetId) || (r.sender_id === targetId && r.receiver_id === user?.id)
    );

  const handleAccept = async (req: FriendRequest) => {
    setActionId(req.id);
    try {
      const { error } = await supabase.from("friend_requests").update({ status: "accepted" }).eq("id", req.id);
      if (error) throw error;
      toast({ title: "Friend request accepted" });
      await refresh();
    } catch (err: any) {
      toast({ title: "Failed", description: err.message, variant: "destructive" });
    } finally { setActionId(null); }
  };

  const handleDecline = async (req: FriendRequest) => {
    setActionId(req.id);
    try {
      const { error } = await supabase.from("friend_requests").update({ status: "rejected" }).eq("id", req.id);
      if (error) throw error;
      toast({ title: "Request declined" });
      await refresh();
    } catch (err: any) {
      toast({ title: "Failed", description: err.message, variant: "destructive" });
    } finally { setActionId(null); }
  };

  const handleCancel = async (req: FriendRequest) => {
    setActionId(req.id);
    try {
      const { error } = await supabase.from("friend_requests").delete().eq("id", req.id);
      if (error) throw error;
      toast({ title: "Request canceled" });
      await refresh();
    } catch (err: any) {
      toast({ title: "Failed", description: err.message, variant: "destructive" });
    } finally { setActionId(null); }
  };

  const handleRemove = async (req: FriendRequest) => {
    setActionId(req.id);
    try {
      if (req.sender_id === user?.id) {
        const { error } = await supabase.from("friend_requests").delete().eq("id", req.id);
        if (error) throw error;
      } else {
        const { error } = await supabase.from("friend_requests").update({ status: "rejected" }).eq("id", req.id);
        if (error) throw error;
      }
      toast({ title: "Friend removed" });
      await refresh();
    } catch (err: any) {
      toast({ title: "Failed", description: err.message, variant: "destructive" });
    } finally { setActionId(null); }
  };

  const handleSend = async (targetId: string) => {
    if (!user) return;
    const existing = findRequestWith(targetId);
    if (existing?.status === "accepted") { toast({ title: "Already friends" }); return; }
    if (existing?.status === "pending") {
      if (existing.receiver_id === user.id) { await handleAccept(existing); }
      else { toast({ title: "Request already sent" }); }
      return;
    }
    setActionId(targetId);
    try {
      const { error } = await supabase.from("friend_requests").insert({ sender_id: user.id, receiver_id: targetId, status: "pending" });
      if (error) throw error;
      toast({ title: "Friend request sent" });
      setJustSent((prev) => new Set(prev).add(targetId));
      await refresh();
    } catch (err: any) {
      toast({ title: "Failed", description: err.message, variant: "destructive" });
    } finally { setActionId(null); }
  };

  const searchWithStatus = useMemo(
    () => searchResults.map((p) => {
      const req = findRequestWith(p.user_id);
      let status: "none" | "incoming" | "outgoing" | "accepted" = "none";
      if (req?.status === "accepted") status = "accepted";
      else if (req?.status === "pending")
        status = req.receiver_id === user?.id ? "incoming" : "outgoing";
      return { profile: p, status, request: req };
    }),
    [searchResults, friendRequests, user?.id]
  );

  const squadFriends = useMemo(
    () => accepted.map((req) => {
      const otherId = req.sender_id === user?.id ? req.receiver_id : req.sender_id;
      const p = profileMap.get(otherId);
      return { userId: otherId, rlName: getDisplayName(p), avatarUrl: p?.avatar_url ?? null };
    }),
    [accepted, profileMap, user?.id]
  );

  const getRankBadge = (userId: string, rankMap: Map<string, string>) => {
    const tier = rankMap.get(userId);
    if (!tier || tier === "unranked") return null;
    return { tier, label: RANK_LABELS[tier] ?? tier, color: RANK_COLORS[tier] ?? "text-foreground" };
  };

  if (authLoading || loading) {
    return (
      <AppLayout>
        <div className="flex items-center justify-center py-20">
          <Loader2 className="w-8 h-8 animate-spin text-primary" />
        </div>
      </AppLayout>
    );
  }

  if (!user) return null;

  return (
    <AppLayout>
      <div className="space-y-4">

        {/* Compact header: title + tab pills in one row */}
        <div className="flex items-center justify-between gap-3">
          <h1 className="text-2xl font-display font-bold">Friends</h1>
          <div className="flex gap-0.5 p-0.5 rounded-lg bg-muted/40 border border-border/50">
            <button
              onClick={() => setPageTab("friends")}
              className={cn(
                "flex items-center gap-1.5 px-3 py-1 rounded-md text-xs font-medium transition-colors",
                pageTab === "friends"
                  ? "bg-card text-foreground shadow-sm"
                  : "text-muted-foreground hover:text-foreground"
              )}
            >
              <Users className="w-3.5 h-3.5" />
              Friends
              {accepted.length > 0 && (
                <span className="bg-primary/20 text-primary text-[10px] font-bold rounded-full px-1.5 leading-none py-0.5">
                  {accepted.length}
                </span>
              )}
            </button>
            <button
              onClick={() => setPageTab("squad")}
              className={cn(
                "flex items-center gap-1.5 px-3 py-1 rounded-md text-xs font-medium transition-colors",
                pageTab === "squad"
                  ? "bg-card text-foreground shadow-sm"
                  : "text-muted-foreground hover:text-foreground"
              )}
            >
              <Users2 className="w-3.5 h-3.5" />
              Squad
            </button>
          </div>
        </div>

        {pageTab === "squad" && (
          <SquadTab friends={squadFriends} loadingFriends={loading} />
        )}

        {pageTab === "friends" && (
          <>
            {/* Horizontal scrollable avatar strip */}
            {accepted.length > 0 && (
              <div className="flex gap-3 overflow-x-auto pb-1 scrollbar-hide -mx-1 px-1">
                {accepted.map((req) => {
                  const otherId = req.sender_id === user.id ? req.receiver_id : req.sender_id;
                  const p = profileMap.get(otherId);
                  const name = getDisplayName(p);
                  return (
                    <Link
                      key={req.id}
                      to={`/profile/${otherId}`}
                      className="flex flex-col items-center gap-1 w-14 shrink-0 group"
                    >
                      <div className="w-11 h-11 rounded-full border-2 border-border/60 group-hover:border-primary/60 transition-colors bg-muted/60 overflow-hidden flex items-center justify-center font-bold text-xs text-muted-foreground">
                        {p?.avatar_url ? (
                          <img src={p.avatar_url} alt={name} className="w-full h-full object-cover" />
                        ) : (
                          <span>{name.slice(0, 2).toUpperCase()}</span>
                        )}
                      </div>
                      <span className="text-[10px] text-muted-foreground truncate w-full text-center leading-tight group-hover:text-foreground transition-colors">
                        {name}
                      </span>
                    </Link>
                  );
                })}
              </div>
            )}

            {/* Incoming Requests — elevated above search */}
            {incoming.length > 0 && (
              <div className="space-y-2">
                <div className="flex items-center gap-2">
                  <p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
                    Requests
                  </p>
                  <span className="bg-amber-500/20 text-amber-400 text-[10px] font-bold rounded-full px-1.5 py-0.5 leading-none">
                    {incoming.length}
                  </span>
                </div>
                {incoming.map((req) => {
                  const p = profileMap.get(req.sender_id);
                  const name = getDisplayName(p);
                  return (
                    <div
                      key={req.id}
                      className="flex items-center gap-3 p-3 rounded-xl border border-border/40 bg-card/60 border-l-2 border-l-amber-400/70"
                    >
                      <Avatar src={p?.avatar_url ?? null} name={name} />
                      <div className="flex-1 min-w-0">
                        <p className="font-display text-sm font-semibold truncate">{name}</p>
                        {shouldShowUsername(p) && (
                          <p className="text-xs text-muted-foreground">@{p!.username}</p>
                        )}
                      </div>
                      <div className="flex items-center gap-1.5 shrink-0">
                        <Button
                          size="sm"
                          variant="hero"
                          disabled={actionId === req.id}
                          onClick={() => handleAccept(req)}
                          className="h-7 px-3 text-xs"
                        >
                          {actionId === req.id ? <Loader2 className="w-3 h-3 animate-spin" /> : "Accept"}
                        </Button>
                        <Button
                          size="sm"
                          variant="ghost"
                          disabled={actionId === req.id}
                          onClick={() => handleDecline(req)}
                          className="h-7 px-2 text-xs text-muted-foreground hover:text-destructive"
                        >
                          Decline
                        </Button>
                      </div>
                    </div>
                  );
                })}
              </div>
            )}

            {/* Inline debounced search */}
            <div className="relative">
              <div className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground pointer-events-none">
                {searching
                  ? <Loader2 className="w-4 h-4 animate-spin" />
                  : <Search className="w-4 h-4" />
                }
              </div>
              <Input
                placeholder="Search players by username or RL name…"
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="pl-9 pr-9 h-9 bg-muted/30 border-border/40 focus:bg-background"
              />
              {searchQuery && (
                <button
                  onClick={() => { setSearchQuery(""); setSearchResults([]); }}
                  className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground transition-colors"
                >
                  <X className="w-3.5 h-3.5" />
                </button>
              )}
            </div>

            {/* Search results */}
            {searchWithStatus.length > 0 && (
              <div className="rounded-xl border border-border/40 bg-card/60 divide-y divide-border/30 overflow-hidden">
                {searchWithStatus.map(({ profile, status, request }) => {
                  const name = getDisplayName(profile);
                  const rank = getRankBadge(profile.user_id, searchRanks);
                  return (
                    <div key={profile.user_id} className="flex items-center gap-3 p-3">
                      <Avatar src={profile.avatar_url} name={name} size="sm" />
                      <div className="flex-1 min-w-0">
                        <p className="font-display text-sm font-semibold truncate">{name}</p>
                        <div className="flex items-center gap-1.5 flex-wrap">
                          {shouldShowUsername(profile) && (
                            <span className="text-[10px] text-muted-foreground">@{profile.username}</span>
                          )}
                          {rank && (
                            <div className="flex items-center gap-0.5">
                              <img src={getRankIcon(rank.tier)} alt={rank.label} className="w-3 h-3 object-contain" />
                              <span className={cn("text-[10px] font-semibold", rank.color)}>{rank.label}</span>
                            </div>
                          )}
                        </div>
                      </div>
                      <div className="flex items-center gap-1.5 shrink-0">
                        {status === "accepted" && (
                          <Badge variant="secondary" className="text-[10px]">Friends</Badge>
                        )}
                        {status === "outgoing" && (
                          <Badge variant="outline" className="text-[10px]">Pending</Badge>
                        )}
                        {status === "incoming" && request && (
                          <>
                            <Button size="sm" variant="hero" disabled={actionId === request.id} onClick={() => handleAccept(request)} className="h-7 px-2.5 text-xs">Accept</Button>
                            <Button size="sm" variant="ghost" disabled={actionId === request.id} onClick={() => handleDecline(request)} className="h-7 px-2 text-xs">Decline</Button>
                          </>
                        )}
                        {status === "none" && (
                          justSent.has(profile.user_id) ? (
                            <span className="flex items-center gap-1 text-xs text-rl-green font-medium">
                              <CheckCircle2 className="w-3.5 h-3.5" />
                              Sent!
                            </span>
                          ) : (
                            <Button
                              size="sm"
                              variant="hero"
                              onClick={() => handleSend(profile.user_id)}
                              disabled={actionId === profile.user_id}
                              className="h-7 px-2.5 text-xs gap-1"
                            >
                              <UserPlus className="w-3 h-3" />
                              Add
                            </Button>
                          )
                        )}
                      </div>
                    </div>
                  );
                })}
              </div>
            )}

            {/* Friends list */}
            {accepted.length === 0 && !searchQuery ? (
              <div className="py-12 text-center space-y-3">
                <Users className="w-10 h-10 text-muted-foreground/30 mx-auto" />
                <p className="font-display font-semibold">No friends yet</p>
                <p className="text-sm text-muted-foreground">Search for players by username or RL name</p>
              </div>
            ) : (
              accepted.length > 0 && (
                <div className="space-y-1.5">
                  <p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground px-0.5">
                    Your Friends · {accepted.length}
                  </p>
                  {accepted.map((req) => {
                    const otherId = req.sender_id === user.id ? req.receiver_id : req.sender_id;
                    const p = profileMap.get(otherId);
                    const name = getDisplayName(p);
                    const rank = getRankBadge(otherId, friendRanks);
                    return (
                      <div
                        key={req.id}
                        className="flex items-center gap-3 p-3 rounded-xl border border-border/40 bg-card/60 hover:bg-card/80 transition-colors"
                      >
                        <Avatar src={p?.avatar_url ?? null} name={name} />
                        <div className="flex-1 min-w-0">
                          <p className="font-display text-sm font-semibold truncate">{name}</p>
                          {rank ? (
                            <div className="flex items-center gap-1 mt-0.5">
                              <img src={getRankIcon(rank.tier)} alt={rank.label} className="w-3.5 h-3.5 object-contain" />
                              <span className={cn("text-[10px] font-semibold", rank.color)}>{rank.label}</span>
                            </div>
                          ) : shouldShowUsername(p) ? (
                            <p className="text-xs text-muted-foreground">@{p!.username}</p>
                          ) : null}
                        </div>
                        <div className="flex items-center gap-1 shrink-0">
                          <Link to={`/profile/${otherId}`}>
                            <Button size="sm" variant="hero" className="h-7 px-3 text-xs">
                              View
                            </Button>
                          </Link>
                          <DropdownMenu>
                            <DropdownMenuTrigger asChild>
                              <Button
                                size="sm"
                                variant="ghost"
                                className="h-7 w-7 p-0 text-muted-foreground hover:text-foreground"
                                disabled={actionId === req.id}
                              >
                                {actionId === req.id
                                  ? <Loader2 className="w-3.5 h-3.5 animate-spin" />
                                  : <MoreHorizontal className="w-3.5 h-3.5" />
                                }
                              </Button>
                            </DropdownMenuTrigger>
                            <DropdownMenuContent align="end" className="w-32">
                              <DropdownMenuItem
                                className="text-destructive focus:text-destructive"
                                onClick={() => handleRemove(req)}
                              >
                                Remove Friend
                              </DropdownMenuItem>
                            </DropdownMenuContent>
                          </DropdownMenu>
                        </div>
                      </div>
                    );
                  })}
                </div>
              )
            )}

            {/* Outgoing requests — compact */}
            {outgoing.length > 0 && (
              <div className="space-y-1.5">
                <p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground px-0.5">
                  Pending
                </p>
                {outgoing.map((req) => {
                  const p = profileMap.get(req.receiver_id);
                  const name = getDisplayName(p);
                  return (
                    <div
                      key={req.id}
                      className="flex items-center gap-3 p-2.5 rounded-xl border border-border/30 bg-muted/20"
                    >
                      <Avatar src={p?.avatar_url ?? null} name={name} size="sm" />
                      <span className="flex-1 text-sm text-muted-foreground truncate">{name}</span>
                      <Badge variant="outline" className="text-[10px] text-muted-foreground shrink-0">Pending</Badge>
                      <Button
                        size="sm"
                        variant="ghost"
                        disabled={actionId === req.id}
                        onClick={() => handleCancel(req)}
                        className="h-6 px-2 text-xs text-muted-foreground hover:text-destructive shrink-0"
                      >
                        Cancel
                      </Button>
                    </div>
                  );
                })}
              </div>
            )}
          </>
        )}
      </div>
    </AppLayout>
  );
};

export default Friends;
